// File generated by FlutterFire CLI.

// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPV3mxnZoAfQT-HRHjoQS5kU-pNYeBBBc',
    appId: '1:189656676098:android:dc6475f100a73a218c741b',
    messagingSenderId: '189656676098',
    projectId: 'abdallah-chat-app',
    storageBucket: 'abdallah-chat-app.firebasestorage.app',
  );
}